### PR TITLE
New York Times Clone

### PR DESCRIPTION
**Pull request by DejazmachMolla**
Positioning and Floating Elements

- Positioned Navbar and its elements
- Positioned different width content
- Used Grid and Flexbox layouts 
- Created the layout for the footer

### CODE REVIEW

**Comment by rammazzoti2000** [comment]
## Code Review Request Invalid :no_entry: 
### Hello team :wave: it seems that your project is missing a readme file description :sob: 

Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

Cheers and Happy coding! :clap: 

##### Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :no_entry: Status: Invalid

**Review by lucasmazo32 — CHANGES_REQUESTED** [review]
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved kindly implement these changes:

## Required changes:

- [ ] Please add the expand section that is at the bottom and sticks at the bottom.
> image


### Happy coding! :computer:

## Lucas Mazo

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi **TEAM**, Congratulations on fixing all recommended changes identified by the previous TSE :slightly_smiling_face: Now, I hereby approve of your project :clinking_glasses: 
You can go ahead ad merge to master, do not forget to submit the project completion form :smile: 

Good luck with your next projects
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Haroonabdulrazaq** [comment]
Thanks

**Pull request merged**
